# Generated by Django 2.0 on 2018-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180126_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharma',
            name='meds',
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharma',
            field=models.ManyToManyField(related_name='pharma', to='accounts.Pharma'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='company',
        ),
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
